####################################################################################################
# AUTHELIA CONFIGURATION FILE
# https://www.authelia.com/configuration/prologue/introduction/
####################################################################################################

# IMPORTANT change port here if changed in docker compose
server:
  address: "tcp://0.0.0.0:9091"

# domain authelia will run under, this has to be commented out when using cookies!
#default_redirection_url: https://auth.<DOMAIN.TLD HERE>
totp:
  # issuer: ROOT domain authelia will run under
  issuer: <DOMAIN.TLD HERE>
  period: 30
  skew: 1

# AUTHENTICATION BACKEND SETTINGS
# IMPORTANT make sure the /config/users_database.yml exists
authentication_backend:
  password_reset:
    disable: true
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

# ACCESS CONTROL SETTINGS
access_control:
  default_policy: deny
  networks:
    # requests from internal networks will not have to authenticate
    - name: internal
      networks:
        - 172.18.0.0/16

  rules:
    # rules applied to everyone
    - domain:
        - "auth.<DOMAIN.TLD HERE>"
      policy: bypass

    - domain: "*.<DOMAIN.TLD HERE>"
      networks:
        # these networks can bypass all rules
        - <NETWORK HERE>
      policy: bypass

    - domain:
        # domains listed here will have authentication screen
        - "<SUBDOMAIN HERE>.<DOMAIN.TLD HERE>"
      subject:
        # users in groups can authenticate
        - "group:admins"
     # authenticate using username and password
      policy: one_factor

# configuration of sessions and cookies
session:
  name: "authelia_session"
  # IMPORTANT generate a value here using
  # openssl rand -hex 64
  secret: "<SECRET HERE"
  same_site: "lax"
  inactivity: "1h"
  expiration: "2h"
  remember_me: "24h"

  # cookie settings for sessions
  cookies:
    - domain: "<DOMAIN.TLD HERE>"
      authelia_url: "https://auth.<DOMAIN.TLD HERE>"
      default_redirection_url: "https://<DOMAIN.TLD HERE>"
      name: "authelia_session"
      same_site: "lax"
      inactivity: "5m"
      expiration: "1h"
      remember_me: "7d"

  redis:
    host: authelia-redis
    port: 6379

# REGULATION SETTINGS
# limit amount of login attempts
# ban account if more than 5 failed attempts
regulation:
  max_retries: 5
  find_time: 2m
  ban_time: 10m


# STORAGE SETTINGS
storage:
  # IMPORTANT generate a value here using
  # openssl rand -hex 64
  encryption_key: <SECRET HERE>
  local:
    path: /config/db.sqlite3

# NOTIFIER SETTINGS
# set this up to send notifications to users
# IMPORTANT this needs to be enabled if you dont set up anything else
notifier:
  filesystem:
    filename: /config/notification.txt

# LOG SETTINGS
# log everything to a file, can be read by fail2ban
# email disabled
log:
  file_path: /var/log/authelia/authelia.log
  keep_stdout: true
  format: text
  level: info
#  smtp:
#    username: <your-user@your-email-domain.org>
#    password: <your-user-email-password-for-smtp>
#    host: <your-email-host-url-or-ip>
#    port: <your-email-port-for-smtp>  # 25 non-ssl, 443 ssl, 587 tls
#    sender: <sender@your-email-domain.org>
#    subject: "[Authelia] {title}"
#    disable_require_tls: false # set to true if your domain uses no tls or ssl only
#    disable_html_emails: false # set to true if you don't want html in your emails
#    tls:
#      server_name: <your-email-host-url-or-ip>
#      skip_verify: false
#      minimum_version: TLS1.2

# THEME SETTINGS
# either light, dark, grey or auto (switch depending on users browser preference)
theme: dark
