# CHANGEDETECTION DOCKER COMPOSE
# Deploys changedetection
# Joins internal docker network
# Changedetection:
#   data:   VOLUME changedetection-data
version: '3.8'

services:
  changedetection:
    container_name: changedetection
    image: dgtlmoon/changedetection.io
    restart: unless-stopped
    expose:
      - 5000
    volumes:
       - changedetection-data:/datastore
    environment:
      TZ: 'Europe/Berlin'

volumes:
  changedetection-data:

networks:
  default:
    external: true
    name: int-docker-net