# CHANGEDETECTION DOCKER COMPOSE
# https://github.com/dgtlmoon/changedetection.io
version: "3.9"

services:
  changedetection:
    container_name: changedetection
    image: dgtlmoon/changedetection.io
    restart: unless-stopped
    expose:
      - 5000
    volumes:
      - changedetection-data:/datastore
    environment:
      - TZ='Europe/Berlin'

volumes:
  changedetection-data:

networks:
  default:
    external: true
    name: int-docker-net
