# CHANGEDETECTION DOCKER COMPOSE
# https://github.com/dgtlmoon/changedetection.io

services:
  app:
    image: dgtlmoon/changedetection.io
    restart: unless-stopped
    expose:
      - 5000
    volumes:
      - app-data:/datastore
    environment:
      - TZ=Europe/Berlin
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - default

volumes:
  app-data:

networks:
  default:
    external: true
    name: int-docker-net
