# MEDIAWIKI COMPOSE
# Deploys mediawiki and mariadb
# Joins internal docker network
# Creates internal mediawiki network
# mediawiki:
#   images:  VOLUME mediawiki-images 100GB
# mariadb:
#   data:    VOLUME mediawiki-db
version: '3.8'

services:
  mediawiki:
    container_name: mediawiki-wiki
    image: mediawiki
    restart: unless-stopped
    expose:
      - 80
    networks:
      - int-docker-net
      - int-mediawiki-net
    volumes:
      - mediawiki-images:/var/www/html/images
      # Mounting config file after initial start
      # - /etc/mediawiki/LocalSettings.php:/var/www/html/LocalSettings.php
    environment:
      TZ: 'Europe/Berlin'

  mariadb:
    container_name: mediawiki-db
    image: mariadb
    restart: unless-stopped
    networks:
      - int-mediawiki-net
    environment:
      MYSQL_DATABASE: <DATABASE NAME HERE>
      MYSQL_USER: <USERNAME HERE>
      MYSQL_PASSWORD: <PASSWORD HERE>
      # LEAVE TO GENERATE RANDOM ROOT PASSWORD FOR INSTANCE
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - mediawiki-db:/var/lib/mysql
    labels:
      - traefik.enable=true
      - traefik.http.routers.<NAME>.entrypoints=web

volumes:
  # limit image volume to 100GB
  mediawiki-images:
    name: mediawiki-images
  mediawiki-db:
    name: mediawiki-db

networks:
  default:
     external: true
     name: int-docker-net
  int-mediawiki-net: