# MEDIAWIKI COMPOSE
# https://github.com/wikimedia/mediawiki
# MediaWiki, MariaDB

services:
  mediawiki:
    container_name: mediawiki-wiki
    hostname: mediawiki-wiki
    image: mediawiki
    restart: unless-stopped
    expose:
      - 80
    networks:
      - int-docker-net
      - int-mediawiki-net
    volumes:
      - mediawiki-images:/var/www/html/images
      # Mounting config file after initial start
      # - /etc/mediawiki/LocalSettings.php:/var/www/html/LocalSettings.php
    environment:
      - TZ=Europe/Berlin

  mariadb:
    container_name: mediawiki-db
    hostname: mediawiki-db
    image: mariadb
    restart: unless-stopped
    volumes:
      - mediawiki-db:/var/lib/mysql
    environment:
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=<DATABASE NAME HERE>
      - MYSQL_USER=<USERNAME HERE>
      - MYSQL_PASSWORD=<PASSWORD HERE>
      # LEAVE TO GENERATE RANDOM ROOT PASSWORD FOR INSTANCE
      #- MYSQL_RANDOM_ROOT_PASSWORD='yes'
    networks:
      - int-mediawiki-net

volumes:
  mediawiki-images:
    name: mediawiki-images
  mediawiki-db:
    name: mediawiki-db

networks:
  default:
    external: true
    name: int-docker-net
  int-mediawiki-net:
