# PRIVATEBIN DOCKER COMPOSE
# https://github.com/PrivateBin/PrivateBin
# Privatebin
version: "3.9"

services:
  privatebin:
    container_name: privatebin
    image: privatebin/nginx-fpm-alpine
    restart: unless-stopped
    expose:
      - 8080
    read_only: true
    volumes:
      - privatebin-data:/srv/data
      - ./privatebin/cfg:/srv/cfg
    environment:
      - TZ="Europe/Berlin"

volumes:
  privatebin-data:

networks:
  default:
    external: true
    name: int-docker-net
