# TEAMSPEAK 3 SERVER DOCKER COMPOSE
# https://hub.docker.com/_/teamspeak

services:
  server:
    image: teamspeak
    restart: unless-stopped
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      - TZ=Europe/Berlin
      - TS3SERVER_LICENSE=accept
    volumes:
      - server-data:/var/ts3server/
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - default

volumes:
  server-data:

networks:
  default:
    external: true
    name: int-docker-net
