# IT-TOOLS COMPOSE
# https://github.com/CorentinTh/it-tools
# itTools

services:
  it-tools:
    container_name: it-tools
    hostname: it-tools
    image: corentinth/it-tools:latest
    restart: unless-stopped
    expose:
      - 8080
    environment:
      - TZ=Europe/Berlin

networks:
  default:
    external: true
    name: int-docker-net
