# UMAMI COMPOSE
# https://github.com/umami-software/umami

services:
  umami:
    container_name: umami-app
    image: ghcr.io/umami-software/umami:postgresql-latest
    restart: unless-stopped
    expose:
      - 3000
    environment:
      - DATABASE_URL=postgresql://umami:umami@db:5432/umami
      - DATABASE_TYPE=postgresql
      - APP_SECRET=<RANDOM STRING HERE>
      - TZ='Europe/Berlin'
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: umami-db
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=umami
      - POSTGRES_USER=umami
      - POSTGRES_PASSWORD=umami
      - TZ='Europe/Berlin'
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  umami-db-data:

networks:
  default:
    external: true
    name: int-docker-net
