# AUTHELIA DOCKER COMPOSE
# https://github.com/authelia/authelia
# Authelia, Redis
version: "3.9"

services:
  authelia:
    container_name: authelia
    hostname: authelia
    image: authelia/authelia
    restart: unless-stopped
    expose:
      - 9091
    volumes:
      - ./config:/config
      - ./logs:/var/log/authelia
    environment:
      - TZ=Europe/Berlin

  redis:
    container_name: authelia-redis
    hostname: authelia-redis
    image: redis:alpine
    restart: unless-stopped
    expose:
      - 6379
    volumes:
      - authelia-redis:/data
    environment:
      - TZ=Europe/Berlin

volumes:
  authelia-redis:

networks:
  default:
    external: true
    name: int-docker-net
