# AUTHELIA DOCKER COMPOSE
# Deploys authelia service and redis
# Joins internal docker network
# Authelia:
#   config  /etc/authelia
#   logs:   /var/logs/authelia
# Redis:
#   data:   VOLUME authelia-redis
version: '3.8'

services:
  authelia:
    container_name: authelia
    image: authelia/authelia
    restart: unless-stopped
    expose:
      - 9091
    volumes:
      # set location for config files
      - /etc/authelia:/config
      # set location for log files, to be read by fail2ban
      - /var/log/authelia:/var/log/authelia
    environment:
      TZ: 'Europe/Berlin'
      
  redis:
    container_name: authelia-redis
    image: redis:alpine
    restart: unless-stopped
    expose:
      - 6379
    volumes:
      - authelia-redis:/data
    environment:
      TZ: 'Europe/Berlin'

volumes:
  authelia-redis:

networks:
  default:
     external: true
     name: int-docker-net