# AUTHELIA DOCKER COMPOSE
# https://github.com/authelia/authelia
version: "3.9"

services:
  authelia:
    container_name: authelia
    image: authelia/authelia
    restart: unless-stopped
    expose:
      - 9091
    volumes:
      - ./authelia:/config
      - /var/log/authelia:/var/log/authelia
    environment:
      - TZ='Europe/Berlin'

  redis:
    container_name: authelia-redis
    image: redis:alpine
    restart: unless-stopped
    expose:
      - 6379
    volumes:
      - authelia-redis:/data
    environment:
      - TZ='Europe/Berlin'

volumes:
  authelia-redis:

networks:
  default:
    external: true
    name: int-docker-net
