# DENDRITE MATRIX SERVER COMPOSE
# https://github.com/matrix-org/dendrite
# Dendrite, Postgres
# Run create-config.sh before running stack to set values
# Run generate-keys.sh before running stack to generate keys
version: "3.9"

services:
  server:
    container_name: dendrite-server
    hostname: dendrite-server
    image: matrixdotorg/dendrite-monolith:latest
    restart: unless-stopped
    expose:
      - 8008
      - 8448
    volumes:
      # config and key files
      - ./config:/etc/dendrite
      # media files
      - dendrite_media:/var/dendrite/media
      - dendrite_jetstream:/var/dendrite/jetstream
      - dendrite_search_index:/var/dendrite/searchindex
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - default
      - int-dendrite-net

  postgres:
    container_name: dendrite-db
    hostname: dendrite-db
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: <PASSWORD HERE>
      POSTGRES_USER: dendrite
      POSTGRES_DATABASE: dendrite
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dendrite" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - int-dendrite-net

networks:
  default:
    external: true
    name: int-docker-net
  int-dendrite-net:

volumes:
  dendrite_media:
  dendrite_jetstream:
  dendrite_search_index:
