# LINKACE COMPOSE
# https://github.com/Kovah/LinkAce
version: "3.9"

services:
  mariadb:
    image: mariadb:10.7
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - TZ='Europe/Berlin'
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - linkace-db:/var/lib/mysql
    networks:
      - int-linkace-net

  linkace:
    image: linkace/linkace:simple
    restart: unless-stopped
    depends_on:
      - db
    expose:
      - 80
    networks:
      - default
      - int-linkace-net
    volumes:
      - ./.env:/app/.env
      - ./backups:/app/storage/app/backups
      - linkace-logs:/app/storage/logs
    environment:
      - TZ='Europe/Berlin'

volumes:
  linkace-logs:
  linkace-db:

networks:
  default:
    external: true
    name: int-docker-net
  int-linkace-net:
