# TRAEFIK PROXY DOCKER COMPOSE
# https://github.com/traefik/traefik
# Traefik

services:
  traefik:
    container_name: traefik
    # POSSIBLY UPDATE THIS TO USE NEWER VERSION WHEN USING
    image: "traefik:v2.10"
    restart: always
    ports:
      - 80:80
      - 443:443
      # EXPOSE THIS PORT FOR WEB DASHBOARD
      # - 8080:8080
    volumes:
      - ./config:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Possibly add volume here for logs
    environment:
      - TZ='Europe/Berlin'

networks:
  default:
    external: true
    name: int-docker-net
