# TRAEFIK PROXY DOCKER COMPOSE
# https://github.com/traefik/traefik
version: "3.9"

services:
  traefik:
    # POSSIBLY UPDATE THIS TO USE NEWER VERSION WHEN USING
    image: "traefik:v2.10"
    container_name: "traefik"
    ports:
      - 80:80
      - 443:443
      # EXPOSE THIS PORT FOR WEB DASHBOARD
      # - 8080:8080
    volumes:
      - /etc/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  default:
    external: true
    name: int-docker-net
