# TRAEFIK PROXY DOCKER COMPOSE
# https://github.com/traefik/traefik
# Deploys treafik PROXY
# Joins internal docker network
# Treafik:
#   data:   /etc/traefik/
#   docker: /var/run/docker.sock
version: '3'

services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /etc/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  default:
    external: true
    name: int-docker-net