# GRAFANA DOCKER COMPOSE
# https://github.com/grafana/grafana
# https://github.com/prometheus/prometheus
# https://github.com/prometheus-community/postgres_exporter

services:
  grafana-app:
    image: grafana/grafana
    restart: unless-stopped
    expose:
      - 3000
    volumes:
      - app-data:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=FQDN_HERE
      - TZ=Europe/Berlin
      - GF_USERS_AUTO_ASSIGN_ORG=true
      - GF_USERS_AUTO_ASSIGN_ORG_ID=1
      # USE FOLLOWING VARIABLES TO ENABLE Generic OAuth
      #- GF_AUTH_GENERIC_OAUTH_ENABLED="true"
      #- GF_AUTH_GENERIC_OAUTH_NAME=""
      #- GF_AUTH_GENERIC_OAUTH_CLIENT_ID=""
      #- GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=""
      #- GF_AUTH_GENERIC_OAUTH_SCOPES=""
      #- GF_AUTH_GENERIC_OAUTH_AUTH_URL=""
      #- GF_AUTH_GENERIC_OAUTH_TOKEN_URL=""
      #- GF_AUTH_GENERIC_OAUTH_API_URL=""
      #- GF_AUTH_SIGNOUT_REDIRECT_URL=""
      #- GF_AUTH_OAUTH_AUTO_LOGIN=""
      #- GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH=
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - default

  prometheus-server:
    image: prom/prometheus
    restart: unless-stopped
    expose:
      - 9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-server-data:/prometheus
    environment:
      - TZ=Europe/Berlin
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - default

  prometheus-node-exporter:
    image: prom/node-exporter:latest
    restart: unless-stopped
    expose:
      - 9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - default

volumes:
  app-data:
  prometheus-server-data:

networks:
  default:
    external: true
    name: int-docker-net
