# GRAFANA DOCKER COMPOSE
# https://github.com/grafana/grafana
# https://github.com/prometheus/prometheus
# https://github.com/prometheus-community/postgres_exporter
# Grafana, Prometheus, PostgresExporter

services:
  grafana:
    container_name: grafana-app
    hostname: grafana-app
    image: grafana/grafana
    restart: unless-stopped
    expose:
      - 3000
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - TZ=Europe/Berlin
      - GF_SERVER_ROOT_URL=<DOMAIN HERE>
    networks:
      - int-grafana-net
      - int-docker-net

  prometheus:
    container_name: grafana-prometheus
    image: prom/prometheus
    restart: unless-stopped
    expose:
      - 9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    environment:
      - TZ=Europe/Berlin
    networks:
      - int-grafana-net

# Optional: for monitoring postgres database
#  postgresexporter:
#    container_name: grafana-postgresexporter
#    image: quay.io/prometheuscommunity/postgres-exporter
#    restart: unless-stopped
#    expose:
#      - 9187
#    environment:
#      - DATA_SOURCE_NAME=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_ADDRESS}:5432/${POSTGRES_DB}?sslmode=disable
#      - "TZ=Europe/Berlin"

volumes:
  grafana-data:

networks:
  default:
    external: true
    name: int-docker-net
  int-grafana-net:
