###########################################################################
# PROMETHEUS CONFIGURATION
# https://prometheus.io/docs/prometheus/latest/configuration/configuration/
# https://github.com/prometheus/prometheus/blob/release-2.42/config/testdata/conf.good.yml
###########################################################################
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# ALERTMANAGER
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# RULES
# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# SCRAPING TARGETS
scrape_configs:
  # Example for Prometheus scraping itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
