# I, LIBRARIAN COMPOSE
# https://github.com/cgrima/docker_i-librarian
# https://github.com/mkucej/i-librarian-free
# iLibrarian
version: "3.9"

services:
  librarian:
    image: cgrima/i-librarian
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - i-librarian-data:/app/data
    environment:
      TZ: "Europe/Berlin"

volumes:
  i-librarian-data:

networks:
  default:
    external: true
    name: int-docker-net
