# OPEN PROJECT DOCKER COMPOSE
# https://github.com/opf/openproject
# Deploys open project aio
# Joins internal docker network
# Openproject:
#   data:   /etc/openproject/
version: '3.8'

services:
  openproject:
    container_name: openproject
    image: openproject/community:12
    expose:
      - 8080
    environment:
      - OPENPROJECT_HOST__NAME=<DOMAIN HERE>
      - OPENPROJECT_SECRET_KEY_BASE=<SECRET KEY HERE>
      - "TZ=Europe/Berlin"
    volumes:
      - /etc/openproject/pgdata:/var/openproject/pgdata
      - /etc/openproject/assets:/var/openproject/assets
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 1m

networks:
  default:
    external: true
    name: int-docker-net