# OPEN PROJECT AIO DOCKER COMPOSE
# https://github.com/opf/openproject
version: "3.9"

services:
  openproject:
    container_name: openproject
    image: openproject/community:12
    restart: unless-stopped
    expose:
      - 8080
    environment:
      - OPENPROJECT_HOST__NAME=<FULL URL HERE>
      # can use ... to generate secret:
      # head /dev/urandom | tr -dc A-Za-z0-9 | head -c 32 ; echo '' 
      - OPENPROJECT_SECRET_KEY_BASE=<SECRET HERE>
      # USE THIS TO DISABLE HTTPS AT START, SHOULD BE SET TO TRUE IN PRODUCTION
      - OPENPROJECT_HTTPS=false
      - TZ='Europe/Berlin'
    volumes:
      # bind mounts might make more sense here, to clean up of files easier
      - ./pgdata:/var/openproject/pgdata
      - ./assets:/var/openproject/assets

networks:
  default:
    external: true
    name: int-docker-net
