# OPEN PROJECT AIO DOCKER COMPOSE
# https://github.com/opf/openproject
version: "3.9"

services:
  openproject:
    container_name: openproject
    image: openproject/community:12
    expose:
      - 8080
    environment:
      - OPENPROJECT_HOST__NAME=<DOMAIN HERE>
      - OPENPROJECT_SECRET_KEY_BASE=<SECRET KEY HERE>
      - TZ='Europe/Berlin'
    volumes:
      - openproject-pgdata:/var/openproject/pgdata
      - openproject-assets:/var/openproject/assets

volumes:
  openproject-pgdata:
  openproject-assets:

networks:
  default:
    external: true
    name: int-docker-net
