# VIKUNJA DOCKER COMPOSE
# https://vikunja.io/docs/full-docker-example/
version: "3.9"

services:
  mariadb:
    container_name: vikunja-db
    hostname: vikunja-db
    image: mariadb:10
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_USER=vikunja
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=vikunja
    volumes:
      - vikunja-db:/var/lib/mysql
    restart: unless-stopped
    networks:
      int-vikunja-net:
        ipv4_address: 172.27.1.3

  api:
    container_name: vikunja-api
    image: vikunja/api
    environment:
      - VIKUNJA_DATABASE_HOST=vikunja-db
      - VIKUNJA_DATABASE_PASSWORD=secret
      - VIKUNJA_DATABASE_TYPE=mysql
      - VIKUNJA_DATABASE_USER=vikunja
      - VIKUNJA_DATABASE_DATABASE=vikunja
      - VIKUNJA_SERVICE_JWTSECRET=

      - VIKUNJA_SERVICE_FRONTENDURL=https://<FULL URL HERE>/
      # Enable user registration, set to false to disable
      - VIKUNJA_SERVICE_ENABLEREGISTRATION=true
    expose:
      - 3456
    volumes:
      - vikunja-api:/app/vikunja/files
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      default:
      int-vikunja-net:
        ipv4_address: 172.27.1.4
    labels:
      - traefik.enable=true
      - "traefik.http.routers.vikunja-api.rule=Host(`<FULL URL HERE>`) && (PathPrefix(`/api/v1`) || PathPrefix(`/dav/`) || PathPrefix(`/.well-known/`))"
      - traefik.http.routers.vikunja-api.tls=true
      - traefik.http.routers.vikunja-api.tls.certresolver=production
      - traefik.http.routers.vikunja-api.entrypoints=websecure

  frontend:
    container_name: vikunja-frontend
    image: vikunja/frontend
    expose:
      - 80
    environment:
      - VIKUNJA_API_URL=https://<FULL URL HERE>/api/v1
    restart: unless-stopped
    networks:
      default:
      int-vikunja-net:
        ipv4_address: 172.27.1.5
    labels:
      - traefik.enable=true
      - traefik.http.routers.vikunja.entrypoints=websecure
      - traefik.http.routers.vikunja.rule=Host(`<FULL URL HERE>`)
      - traefik.http.routers.vikunja.tls=true
      - traefik.http.routers.vikunja.tls.certresolver=production

volumes:
  vikunja-db:
  vikunja-api:

networks:
  default:
    external: true
    name: int-docker-net

  int-vikunja-net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.27.1.0/28"
