# GRAYLOG DOCKER COMPOSE CONFIGURATION
# https://graylog.org/

services:
  mongo-db:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-db-data:/data/db
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      default:
        ipv4_address: 172.19.200.3

  datanode:
    image: graylog/graylog-datanode:6.1
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - GRAYLOG_DATANODE_NODE_ID_FILE=/var/lib/graylog-datanode/node-id
      - GRAYLOG_DATANODE_PASSWORD_SECRET=${GRAYLOG_PASSWORD_SECRET}
      - GRAYLOG_DATANODE_ROOT_PASSWORD_SHA2=${GRAYLOG_ROOT_PASSWORD_SHA2}
      - GRAYLOG_DATANODE_MONGODB_URI=mongodb://mongo-db:27017/graylog
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - datanode-data:/var/lib/graylog-datanode
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      default:
        ipv4_address: 172.19.200.2

  app:
    image: graylog/graylog:6.1
    restart: unless-stopped
    depends_on:
      graylog-db:
        condition: service_started
    entrypoint: "/usr/bin/tini -- /docker-entrypoint.sh"
    env_file:
      - .env
    environment:
      - GRAYLOG_NODE_ID_FILE=/usr/share/graylog/data/data/node-id
      - GRAYLOG_PASSWORD_SECRET=${GRAYLOG_PASSWORD_SECRET}
      - GRAYLOG_ROOT_PASSWORD_SHA2=${GRAYLOG_ROOT_PASSWORD_SHA2}
      - GRAYLOG_HTTP_BIND_ADDRESS=0.0.0.0:9000
      - GRAYLOG_HTTP_EXTERNAL_URI=${GRAYLOG_DOMAIN}
      - GRAYLOG_MONGODB_URI=mongodb://mongo-db:27017/graylog
      - GRAYLOG_HTTP_ENABLE_CORS=true
    expose:
      - 9000
    volumes:
      - app-data:/usr/share/graylog/data/data
      - app-journal:/usr/share/graylog/data/journal
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      default:
        ipv4_address: 172.19.200.1

volumes:
  mongo-db-data:
  datanode-data:
  app-data:
  app-journal:

networks:
  default:
    external: true
    name: int-docker-net
