# GRAYLOG COMPOSE
# https://github.com/Graylog2/docker-compose/blob/main/open-core/docker-compose.yml
# Graylog, MongoDB, Graylog Datanode
version: "3.9"

services:
  mongodb:
    container_name: graylog-db
    hostname: graylog-db
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - graylog-db:/data/db
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  datanode:
    container_name: graylog-datanode
    hostname: graylog-datanode
    image: graylog/graylog-datanode:5.2
    restart: unless-stopped
    environment:
      - GRAYLOG_DATANODE_NODE_ID_FILE=/var/lib/graylog-datanode/node-id
      - GRAYLOG_DATANODE_PASSWORD_SECRET=${GRAYLOG_PASSWORD_SECRET}
      - GRAYLOG_DATANODE_ROOT_PASSWORD_SHA2=${GRAYLOG_ROOT_PASSWORD_SHA2}
      - GRAYLOG_DATANODE_MONGODB_URI=mongodb://graylog-db:27017/graylog
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    # standard list of ports, left here as a list
    #ports:
    #  - "8999:8999/tcp"   # DataNode API
    #  - "9200:9200/tcp"
    #  - "9300:9300/tcp"
    volumes:
      - graylog-datanode:/var/lib/graylog-datanode
    networks:
      default:
        ipv4_address: 172.19.200.2

  graylog:
    container_name: graylog
    hostname: graylog
    image: graylog/graylog:5.2
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: "service_started"
    entrypoint: "/usr/bin/tini --  /docker-entrypoint.sh"
    environment:
      - GRAYLOG_NODE_ID_FILE=/usr/share/graylog/data/data/node-id
      - GRAYLOG_PASSWORD_SECRET=${GRAYLOG_PASSWORD_SECRET}
      - GRAYLOG_ROOT_PASSWORD_SHA2=${GRAYLOG_ROOT_PASSWORD_SHA2}
      # LEAVE THIS AS IS
      - GRAYLOG_HTTP_BIND_ADDRESS=0.0.0.0:9000
      # SET THIS to domain, but keep the protocol http!
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/
      - GRAYLOG_MONGODB_URI=mongodb://graylog-db:27017/graylog
      # standard list of ports, left here as a list
      #ports:
      #  - "5044:5044/tcp"   # Beats
      #  - "5140:5140/udp"   # Syslog
      #  - "5140:5140/tcp"   # Syslog
      #  - "5555:5555/tcp"   # RAW TCP
      #  - "5555:5555/udp"   # RAW TCP
      #  - "9000:9000/tcp"   # Server API
      #  - "12201:12201/tcp" # GELF TCP
      #  - "12201:12201/udp" # GELF UDP
      #  - "10000:10000/tcp" # Custom TCP port
      #  - "10000:10000/udp" # Custom UDP port
      #  - "13301:13301/tcp" # Forwarder data
      #  - "13302:13302/tcp" # Forwarder config
    expose:
      - 9000
    volumes:
      - "graylog-data:/usr/share/graylog/data/data"
      - "graylog-journal:/usr/share/graylog/data/journal"
    # DISABLE THE HEALTHCHECK, this has to be done, if not, traefik will not recognise this container as it will be unhealthy
    healthcheck:
      disable: true
    networks:
      default:
        ipv4_address: 172.19.200.1

volumes:
  graylog-db:
  graylog-datanode:
  graylog-data:
  graylog-journal:

networks:
  default:
    external: true
    name: int-docker-net
