##########################################################################
# AUTHELIA CONFIGURATION FILE
# https://www.authelia.com/configuration/prologue/introduction/
# https://github.com/authelia/authelia/blob/master/config.template.yml
##########################################################################
host: 0.0.0.0
jwt_secret: <SECRET HERE>
default_redirection_url: https://auth.<DOMAIN HERE>
totp:
  issuer: <DOMAIN HERE>
  period: 30
  skew: 1

# BACKEND
# https://github.com/authelia/authelia/blob/master/config.template.yml#L270
authentication_backend:
  password_reset:
    disable: true
  file:
    # https://github.com/authelia/authelia/blob/master/config.template.yml#L270
    # MAKE SURE THIS FILE EXISTS OR CREATE IT
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

# ACCESS CONTROL
# https://github.com/authelia/authelia/blob/master/config.template.yml#L577
access_control:
  default_policy: deny
  networks:
    - name: internal
      networks:
        - 172.18.0.0/16
  rules:
    # Rules applied to everyone
    - domain:
        - "auth.<DOMAIN HERE>"
      policy: bypass
    # Domains accessible using one factor
    - domain:
        # - <DOMAIN OF SERVICE>"
      policy: one_factor
    # Domains accessible using one factor, only by users in admin group
    - domain:
        # - <DOMAIN OF SERVICE>
      subject:
        - "group:admins"
      policy: one_factor

# SESSION SETTINGS
# https://github.com/authelia/authelia/blob/master/config.template.yml#L693
session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret: <SECRET HERE>
  expiration: 3600 # 1 hour
  inactivity: 7200 # 2 hours
  domain: <DOMAIN HERE> # Needs to be your root domain

  redis:
    # POSSIBLY CHANGE NAME HERE TO REDIS CONTAINER NAME
    host: authelia-redis-1
    port: 6379
    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
    # password: authelia

# REGULATIONS
# https://github.com/authelia/authelia/blob/master/config.template.yml#L916
regulation:
  max_retries: 5
  find_time: 2m
  ban_time: 10m

# options: dark, light
theme: dark

storage:
  encryption_key: <SECRET HERE>
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt

log:
  file_path: /var/log/authelia/authelia.log
  keep_stdout: true
  format: text
  level: info
