# PICOSHARE COMPOSE
# https://github.com/mtlynch/picoshare
# Picoshare
version: "3.9"

services:
  app:
    container_name: picoshare
    image: mtlynch/picoshare
    restart: unless-stopped
    expose:
      - 4001
    volumes:
      - picoshare-data:/data
    command: -db /data/store.db -vacuum true
    environment:
      - TZ='Europe/Berlin'
      - PORT=4001
      - PS_BEHIND_PROXY=true
      - PS_SHARED_SECRET=<SET PASSPHRASE FOR ADMIN LOGIN>

volumes:
  picoshare-data:

networks:
  default:
    external: true
    name: int-docker-net
