# PICOSHARE DOCKER COMPOSE CONFIGURATION
# https://github.com/mtlynch/picoshare

services:
  app:
    image: mtlynch/picoshare:1.4.1
    restart: unless-stopped
    expose:
      - 4001
    volumes:
      - app-data:/data
    command: -db /data/store.db -vacuum true
    env_file:
      - .env
    environment:
      - TZ=Europe/Berlin
      - PORT=4001
      - PS_BEHIND_PROXY=true
      - PS_SHARED_SECRET=${SHARED_SECRET}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - default

volumes:
  app-data:

networks:
  default:
    external: true
    name: int-docker-net
