# FRESHRSS DOCKER COMPOSE
# https://github.com/FreshRSS/FreshRSS

services:
  app:
    image: freshrss/freshrss:latest
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - app-data:/var/www/FreshRSS
    environment:
      - TZ=Europe/Berlin
      - 'CRON_MIN=1,31'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - default

volumes:
  app-data:

networks:
  default:
    external: true
    name: int-docker-net
