# FRESHRSS DOCKER COMPOSE
# https://github.com/FreshRSS/FreshRSS
# FreshRSS
version: "3.9"

services:
  freshrss:
    container_name: freshrss
    image: freshrss/freshrss:latest
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - ./data:/var/www/FreshRSS/data
      - ./data:/var/www/FreshRSS/extensions
    environment:
      - TZ="Europe/Berlin"
      # cron jobs runs at 1 and 31 every hour to refresh the feed
      - CRON_MIN="1,31"
    logging:
      options:
        max-size: "200k"
        max-file: "10"

networks:
  default:
    external: true
    name: int-docker-net
