# FRESHRSS DOCKER COMPOSE
# https://github.com/FreshRSS/FreshRSS
version: "3.9"

services:
  freshrss:
    container_name: freshrss
    image: freshrss/freshrss:latest
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - freshrss-data:/var/www/FreshRSS/data
      - freshrss-data:/var/www/FreshRSS/extensions
    environment:
      - TZ="Europe/Berlin"
      - CRON_MIN="1,31"

volumes:
  freshrss-data:

networks:
  default:
    external: true
    name: int-docker-net
