# STIRLING PDF COMPOSE
# https://github.com/Frooodle/Stirling-PDF
# StirlingPDF

services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    expose:
      - 8080
#   volumes:
#     - /location/of/trainingData:/usr/share/tesseract-ocr/4.00/tessdata #Required for extra OCR languages
#     - /location/of/extraConfigs:/configs
#     - /location/of/customFiles:/customFiles/

networks:
  default:
    external: true
    name: int-docker-net
