# STIRLING PDF DOCKER COMPOSE
# https://github.com/Frooodle/Stirling-PDF

services:
  app:
    image: frooodle/s-pdf:latest
    restart: unless-stopped
    expose:
      - 8080
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - default

networks:
  default:
    external: true
    name: int-docker-net
