# EXCALIDRAW COMPOSE
# https://github.com/excalidraw/excalidraw, https://hub.docker.com/r/excalidraw/excalidraw
# Excalidraw

services:
  app:
    container_name: excalidraw-app
    hostname: excalidraw-app
    image: excalidraw/excalidraw:latest
    restart: unless-stopped
    expose:
      - 80
    environment:
      - TZ=Europe/Berlin

# join existing network for all containers
networks:
  default:
    external: true
    name: int-docker-net
