# SEARXNG COMPOSE
# https://github.com/searxng/searxng
version: "3.9"

services:
  <SERVICE NAME>:
    container_name: searxng
    image: searxng/searxng
    restart: unless-stopped
    expose:
      - 8080
    volumes:
      - searxng-data:/etc/searxng
    environment:
      - TZ='Europe/Berlin'
      - SEARXNG_BASE_URL=https://<FULL URL HERE>/
      - SEARXNG_INSTANCE_NAME=

volumes:
  searxng-data:

networks:
  default:
    external: true
    name: int-docker-net
