# NGINX PROXY MANAGER DOCKER COMPOSE
# Deploys nginx proxy manager
# Joins internal docker network
# Nginx:
#   data:   /etc/nginx-pm/
version: '3.8'

services:
  nginx:
    container_name: nginx
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - /etc/nginx-pm/data:/data
      - /etc/nginx-pm/letsencrypt:/etc/letsencrypt
    environment:
      - "TZ=Europe/Berlin"

networks:
  default:
    external: true
    name: int-docker-net